Feature/practice 6.7 api testing - partially completed
AndreyPanda/DBP_main_course-Task-Manager pull request #18
Opened 2023-03-30 15:04 UTC by AndreyPanda

Practice 6.7 (API testing) is partially done. Added tests for user: create, list.

Здравствуйте, тяжело идет этот раздел. Не уверен, что верно реализовал тесты.
Проверьте, пожалуйста, верна ли моя реализация для user: create, list.
А то затем предстоит еще больше работы и не хочется плодить одни и те же ошибки в следующих тестах.

2023-04-03 06:19 UTC, aleksandr-semenov-dbp requested changes
В общем-то все правильно с учетом комментариев. Да, раздел непростой, и важный для работы над нашими проектами, бОльшую часть времени мы пишем тесты.

2023-04-03 06:19 UTC, aleksandr-semenov-dbp commented on TaskManager/test/test_user.py
> +        user_2_attributes["id"] = user_2.id
чуть выше есть же специальный метод для этого `expected_details()` надо его и применять, заодно и данные свои никакие не попортим, он создает новый dict()

2023-04-03 06:19 UTC, aleksandr-semenov-dbp commented on TaskManager/test/test_user.py
> +        expected_response = [self.user_attributes, user_2_attributes]
```
expected_response = [
    self.expected_details(self.user_attributes, self.user),
    self.expected_details(user2_attributes, self.user2),
]
```

2023-04-03 06:19 UTC, aleksandr-semenov-dbp commented on TaskManager/test/test_user.py
> +        attributes.pop("username")
а куда девается `username`? Надо возвращать (добавить в сериалайзер)

2023-04-03 06:19 UTC, aleksandr-semenov-dbp commented on TaskManager/test/test_user.py
> +        user = self.create(self.user_attributes)
По идее этот юзер уже создан в setUpTestData, надо создавать другого

2023-04-05 05:14 UTC, AndreyPanda commented on TaskManager/test/test_user.py
> +        attributes.pop("username")
Принято, исправлю.

2023-04-05 05:14 UTC, AndreyPanda commented on TaskManager/test/test_user.py
> +        user = self.create(self.user_attributes)
Принято, обновлю.

2023-04-05 05:17 UTC, AndreyPanda commented on TaskManager/test/test_user.py
> +        expected_response = [self.user_attributes, user_2_attributes]
Здесь я, возможно, не до конца разобрался. Но, как я вижу, метод expected_details принимает в качестве аргумента user, который был создан методом create. А мы же в рассматриваемом тестовом методе (test_list) используем create_api_user. В общем, в обновленной версии приложения (следующий PR) я использовал метод expected_details, только аргументы вставил немного иные.

2023-04-05 05:18 UTC, AndreyPanda commented on TaskManager/test/test_user.py
> +        user_2_attributes["id"] = user_2.id
Это замечание перекрывается следующим (см. ниже).

2023-04-10 00:11 UTC, aleksandr-semenov-dbp approved these changes

2023-04-10 04:30 UTC, merged